"""add duration and calories columns

Revision ID: b907c430d8c5
Revises: 58060653a137
Create Date: 2025-03-04 00:42:10.687342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b907c430d8c5'
down_revision: Union[str, None] = '58060653a137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'calories')
    op.drop_column('workouts', 'duration')
    # ### end Alembic commands ###
