"""add_role_column_to_members

Revision ID: b71874fd7c19
Revises: 8e05578bd345
Create Date: 2025-03-09 12:57:55.919115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71874fd7c19'
down_revision: Union[str, None] = '8e05578bd345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
